In [ ]:
#importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [58]:
#importing the dataset
apple_stock = r"C:\Users\hp\Desktop\IBM Day Project\Datasets\AAPL_stock.csv"
apple_df = pd.DataFrame(pd.read_csv(apple_stock))

In [59]:
apple_df.head()

,Price,Close,High,Low,Open,Volume
0,Ticker,AAPL,AAPL,AAPL,AAPL,AAPL
1,Date,NaN,NaN,NaN,NaN,NaN
2,2021-01-04,126.40522003173828,130.5076968368651,123.81674915248705,130.41979013281448,143301900
3,2021-01-05,127.96807861328125,128.68113950331986,125.4479817429498,125.89730757907694,97664900
4,2021-01-06,123.66046905517578,128.0071488340126,123.44557604986173,124.75446642211676,155088000

In [60]:
apple_df.shape

(755, 6)

In [61]:
apple_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 755 entries, 0 to 754
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Price   755 non-null    object
 1   Close   754 non-null    object
 2   High    754 non-null    object
 3   Low     754 non-null    object
 4   Open    754 non-null    object
 5   Volume  754 non-null    object
dtypes: object(6)
memory usage: 35.5+ KB

In [62]:
amazon_stock = r"C:\Users\hp\Desktop\IBM Day Project\Datasets\AMZN_stock.csv"
amazon_df = pd.DataFrame(pd.read_csv(amazon_stock))

In [63]:
amazon_df.head()

,Price,Close,High,Low,Open,Volume
0,Ticker,AMZN,AMZN,AMZN,AMZN,AMZN
1,Date,NaN,NaN,NaN,NaN,NaN
2,2021-01-04,159.3314971923828,163.60000610351562,157.2010040283203,163.5,88228000
3,2021-01-05,160.92550659179688,161.16900634765625,158.2530059814453,158.30050659179688,53110000
4,2021-01-06,156.91900634765625,159.87550354003906,156.55799865722656,157.32400512695312,87896000

In [64]:
amazon_df.shape

(755, 6)

In [65]:
amazon_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 755 entries, 0 to 754
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Price   755 non-null    object
 1   Close   754 non-null    object
 2   High    754 non-null    object
 3   Low     754 non-null    object
 4   Open    754 non-null    object
 5   Volume  754 non-null    object
dtypes: object(6)
memory usage: 35.5+ KB

In [66]:
google_stock = r"C:\Users\hp\Desktop\IBM Day Project\Datasets\GOOGL_stock.csv"
google_df = pd.DataFrame(pd.read_csv(google_stock))

In [67]:
google_df.head()

,Price,Close,High,Low,Open,Volume
0,Ticker,GOOGL,GOOGL,GOOGL,GOOGL,GOOGL
1,Date,NaN,NaN,NaN,NaN,NaN
2,2021-01-04,85.89584350585938,87.705186375187,84.9508603421397,87.58128228878026,37324000
3,2021-01-05,86.58853149414062,86.92591538334669,85.4365378377414,85.84408949685165,20360000
4,2021-01-06,85.73410034179688,86.7835871141567,84.40147477035065,84.6084852313309,46588000

In [68]:
google_df.shape

(755, 6)

In [69]:
google_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 755 entries, 0 to 754
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Price   755 non-null    object
 1   Close   754 non-null    object
 2   High    754 non-null    object
 3   Low     754 non-null    object
 4   Open    754 non-null    object
 5   Volume  754 non-null    object
dtypes: object(6)
memory usage: 35.5+ KB

In [70]:
jpm_stock = r"C:\Users\hp\Desktop\IBM Day Project\Datasets\JPM_stock.csv"
jpm_df = pd.DataFrame(pd.read_csv(jpm_stock))

In [71]:
jpm_df.head()

,Price,Close,High,Low,Open,Volume
0,Ticker,JPM,JPM,JPM,JPM,JPM
1,Date,NaN,NaN,NaN,NaN,NaN
2,2021-01-04,111.6209487915039,113.3856698910516,110.65433820629697,113.06642297903028,16819900
3,2021-01-05,112.22832489013672,112.80889458006544,110.54913829068515,111.6388214717493,13731200
4,2021-01-06,117.49808502197266,118.58776806136176,114.22010217650814,116.00647284189485,24909100

In [72]:
jpm_df.shape

(755, 6)

In [73]:
jpm_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 755 entries, 0 to 754
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Price   755 non-null    object
 1   Close   754 non-null    object
 2   High    754 non-null    object
 3   Low     754 non-null    object
 4   Open    754 non-null    object
 5   Volume  754 non-null    object
dtypes: object(6)
memory usage: 35.5+ KB

In [74]:
meta_stock = r"C:\Users\hp\Desktop\IBM Day Project\Datasets\META_stock.csv"
meta_df = pd.DataFrame(pd.read_csv(meta_stock))

In [75]:
meta_df.head()

,Price,Close,High,Low,Open,Volume
0,Ticker,META,META,META,META,META
1,Date,NaN,NaN,NaN,NaN,NaN
2,2021-01-04,267.67840576171875,273.70997589140853,263.95595980941005,273.49100669571857,15106100
3,2021-01-05,269.6989440917969,271.1222290051814,266.9518808887901,267.0315226371125,9871600
4,2021-01-06,262.0748596191406,266.49403483971406,258.79035145155876,260.7710070140246,24354100

In [76]:
meta_df.shape

(755, 6)

In [77]:
meta_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 755 entries, 0 to 754
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Price   755 non-null    object
 1   Close   754 non-null    object
 2   High    754 non-null    object
 3   Low     754 non-null    object
 4   Open    754 non-null    object
 5   Volume  754 non-null    object
dtypes: object(6)
memory usage: 35.5+ KB

In [78]:
msft_stock = r"C:\Users\hp\Desktop\IBM Day Project\Datasets\MSFT_stock.csv"
msft_df = pd.DataFrame(pd.read_csv(msft_stock))

In [79]:
msft_df.head()

,Price,Close,High,Low,Open,Volume
0,Ticker,MSFT,MSFT,MSFT,MSFT,MSFT
1,Date,NaN,NaN,NaN,NaN,NaN
2,2021-01-04,210.00201416015625,215.12448267035043,207.2237201668687,214.67108011672624,37130100
3,2021-01-05,210.20458984375,210.80270379708463,208.08228847102743,209.58719281314148,23823000
4,2021-01-06,204.75411987304688,208.84438415106663,204.45507027458913,204.676943408944,35930700

In [80]:
msft_df.shape

(755, 6)

In [81]:
msft_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 755 entries, 0 to 754
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Price   755 non-null    object
 1   Close   754 non-null    object
 2   High    754 non-null    object
 3   Low     754 non-null    object
 4   Open    754 non-null    object
 5   Volume  754 non-null    object
dtypes: object(6)
memory usage: 35.5+ KB

In [82]:
nvda_stock = r"C:\Users\hp\Desktop\IBM Day Project\Datasets\NVDA_stock.csv"
nvda_df = pd.DataFrame(pd.read_csv(nvda_stock))

In [83]:
nvda_df.head()

,Price,Close,High,Low,Open,Volume
0,Ticker,NVDA,NVDA,NVDA,NVDA,NVDA
1,Date,NaN,NaN,NaN,NaN,NaN
2,2021-01-04,13.079097747802734,13.616684247552554,12.928493857668233,13.069872326194028,560640000
3,2021-01-05,13.369584083557129,13.408232123108572,13.052667686186886,13.065383910856193,322760000
4,2021-01-06,12.581408500671387,13.210254353866354,12.552983660244543,13.187813339939485,580424000

In [84]:
nvda_df.shape

(755, 6)

In [85]:
nvda_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 755 entries, 0 to 754
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Price   755 non-null    object
 1   Close   754 non-null    object
 2   High    754 non-null    object
 3   Low     754 non-null    object
 4   Open    754 non-null    object
 5   Volume  754 non-null    object
dtypes: object(6)
memory usage: 35.5+ KB

In [86]:
tesla_stock = r"C:\Users\hp\Desktop\IBM Day Project\Datasets\TSLA_stock.csv"
tesla_df = pd.DataFrame(pd.read_csv(tesla_stock))

In [87]:
tesla_df.head()

,Price,Close,High,Low,Open,Volume
0,Ticker,TSLA,TSLA,TSLA,TSLA,TSLA
1,Date,NaN,NaN,NaN,NaN,NaN
2,2021-01-04,243.2566680908203,248.163330078125,239.06333923339844,239.82000732421875,145914600
3,2021-01-05,245.0366668701172,246.94667053222656,239.73333740234375,241.22000122070312,96735600
4,2021-01-06,251.9933319091797,258.0,249.6999969482422,252.8300018310547,134100000

In [88]:
tesla_df.shape

(755, 6)

In [89]:
tesla_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 755 entries, 0 to 754
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Price   755 non-null    object
 1   Close   754 non-null    object
 2   High    754 non-null    object
 3   Low     754 non-null    object
 4   Open    754 non-null    object
 5   Volume  754 non-null    object
dtypes: object(6)
memory usage: 35.5+ KB

In [90]:
v_stock = r"C:\Users\hp\Desktop\IBM Day Project\Datasets\V_stock.csv"
v_df = pd.DataFrame(pd.read_csv(v_stock))

In [91]:
v_df.head()

,Price,Close,High,Low,Open,Volume
0,Ticker,V,V,V,V,V
1,Date,NaN,NaN,NaN,NaN,NaN
2,2021-01-04,211.1414031982422,213.5557275326483,207.72840063423934,213.5557275326483,10318300
3,2021-01-05,207.99014282226562,211.82009771541138,207.14659047826174,209.7354362883176,6869700
4,2021-01-06,206.1576385498047,209.59974306867468,205.6243670455552,207.3017814095906,7206200

In [92]:
v_df.shape

(755, 6)

In [93]:
v_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 755 entries, 0 to 754
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Price   755 non-null    object
 1   Close   754 non-null    object
 2   High    754 non-null    object
 3   Low     754 non-null    object
 4   Open    754 non-null    object
 5   Volume  754 non-null    object
dtypes: object(6)
memory usage: 35.5+ KB

In [94]:
wmt_stock = r"C:\Users\hp\Desktop\IBM Day Project\Datasets\WMT_stock.csv"
wmt_df = pd.DataFrame(pd.read_csv(wmt_stock))

In [95]:
wmt_df.head()

,Price,Close,High,Low,Open,Volume
0,Ticker,WMT,WMT,WMT,WMT,WMT
1,Date,NaN,NaN,NaN,NaN,NaN
2,2021-01-04,45.945159912109375,46.05803857212014,45.23966200743328,45.24593085122127,32182200
3,2021-01-05,45.700584411621094,46.11447880423378,45.305507315052076,45.96710894702222,26498100
4,2021-01-06,45.98591995239258,46.437441769096516,45.46855554000636,45.4936416802001,21918900

In [96]:
wmt_df.shape

(755, 6)

In [97]:
wmt_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 755 entries, 0 to 754
Data columns (total 6 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   Price   755 non-null    object
 1   Close   754 non-null    object
 2   High    754 non-null    object
 3   Low     754 non-null    object
 4   Open    754 non-null    object
 5   Volume  754 non-null    object
dtypes: object(6)
memory usage: 35.5+ KB

In [98]:
#Checking missing values
apple_Missing_value = apple_df.isna().sum()
print(apple_Missing_value)

Price     0
Close     1
High      1
Low       1
Open      1
Volume    1
dtype: int64

In [108]:
# Drop the first two rows
apple_df_cleaned = apple_df.drop(index=[0, 1]).reset_index(drop=True)

In [111]:
apple_df_cleaned.isna().sum()

Price     0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [142]:
apple_df_cleaned.rename(columns={'Price': 'Date'}, inplace=True)

In [163]:
apple_df_cleaned.sample()

,Date,Close,High,Low,Open,Volume
308,2022-03-24,171.29441833496094,171.363294359729,167.49596638171184,168.33240391380366,90131400

In [164]:
amazon_Missing_value = amazon_df.isna().sum()
print(amazon_Missing_value)

Price     0
Close     1
High      1
Low       1
Open      1
Volume    1
dtype: int64

In [113]:
amazon_df_cleaned = amazon_df.drop(index=[0, 1]).reset_index(drop=True)

In [114]:
amazon_df_cleaned.isna().sum()

Price     0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [161]:
amazon_df_cleaned.rename(columns={'Price': 'Date'}, inplace=True)

In [162]:
amazon_df_cleaned.sample()

,Date,Close,High,Low,Open,Volume
43,2021-03-08,147.59750366210938,153.22950744628906,147.5655059814453,150.75,83700000

In [100]:
google_Missing_value = google_df.isna().sum()
print(google_Missing_value)

Price     0
Close     1
High      1
Low       1
Open      1
Volume    1
dtype: int64

In [115]:
google_df_cleaned = google_df.drop(index=[0, 1]).reset_index(drop=True)

In [116]:
google_df_cleaned.isna().sum()

Price     0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [165]:
google_df_cleaned.rename(columns={'Price': 'Date'}, inplace=True)

In [166]:
google_df_cleaned.sample()

,Date,Close,High,Low,Open,Volume
126,2021-07-06,125.58956909179688,125.8264356149296,123.9897120776106,125.05064175261214,26404000

In [101]:
jpm_Missing_value = jpm_df.isna().sum()
print(jpm_Missing_value)

Price     0
Close     1
High      1
Low       1
Open      1
Volume    1
dtype: int64

In [117]:
jpm_df_cleaned = jpm_df.drop(index=[0, 1]).reset_index(drop=True)

In [118]:
jpm_df_cleaned.isna().sum()

Price     0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [156]:
jpm_df_cleaned.rename(columns={'Price': 'Date'}, inplace=True)

In [157]:
jpm_df_cleaned.sample()

,Date,Close,High,Low,Open,Volume
368,2022-06-21,106.71334075927734,107.81888924605573,105.98551864440098,106.75019331269074,11680500

In [102]:
meta_Missing_value = meta_df.isna().sum()
print(meta_Missing_value)

Price     0
Close     1
High      1
Low       1
Open      1
Volume    1
dtype: int64

In [119]:
meta_df_cleaned = meta_df.drop(index=[0, 1]).reset_index(drop=True)

In [121]:
meta_df_cleaned.isna().sum()

Price     0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [153]:
meta_df_cleaned.rename(columns={'Price': 'Date'}, inplace=True)

In [154]:
meta_df_cleaned.sample()

,Date,Close,High,Low,Open,Volume
64,2021-04-07,311.621337890625,312.7759001486744,304.06694509282426,304.9030011332549,22855200

In [103]:
msft_Missing_value = msft_df.isna().sum()
print(msft_Missing_value)

Price     0
Close     1
High      1
Low       1
Open      1
Volume    1
dtype: int64

In [130]:
msft_df_cleaned = msft_df.drop(index=[0, 1]).reset_index(drop=True)

In [131]:
msft_df_cleaned.isna().sum()

Price     0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [158]:
msft_df_cleaned.rename(columns={'Price': 'Date'}, inplace=True)

In [159]:
msft_df_cleaned.sample()

,Date,Close,High,Low,Open,Volume
79,2021-04-28,246.135498046875,248.04998184217743,244.5787793719644,247.60518400104692,46903100

In [104]:
nvda_Missing_value = nvda_df.isna().sum()
print(nvda_Missing_value)

Price     0
Close     1
High      1
Low       1
Open      1
Volume    1
dtype: int64

In [128]:
nvda_df_cleaned = nvda_df.drop(index=[0, 1]).reset_index(drop=True)

In [129]:
nvda_df_cleaned.isna().sum()

Price     0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [150]:
nvda_df_cleaned.rename(columns={'Price': 'Date'}, inplace=True)

In [151]:
nvda_df_cleaned.sample()

,Date,Close,High,Low,Open,Volume
486,2022-12-07,16.10680389404297,16.172749846641757,15.654173729604334,15.759088264862537,372388000

In [105]:
tesla_Missing_value = tesla_df.isna().sum()
print(tesla_Missing_value)

Price     0
Close     1
High      1
Low       1
Open      1
Volume    1
dtype: int64

In [126]:
tesla_df_cleaned = tesla_df.drop(index=[0, 1]).reset_index(drop=True)

In [127]:
tesla_df_cleaned.isna().sum()

Price     0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [148]:
tesla_df_cleaned.rename(columns={'Price': 'Date'}, inplace=True)

In [149]:
tesla_df_cleaned.sample()

,Date,Close,High,Low,Open,Volume
704,2023-10-20,211.99000549316406,218.86000061035156,210.4199981689453,217.00999450683594,137734000

In [106]:
v_Missing_value = v_df.isna().sum()
print(v_Missing_value)

Price     0
Close     1
High      1
Low       1
Open      1
Volume    1
dtype: int64

In [124]:
v_df_cleaned = v_df.drop(index=[0, 1]).reset_index(drop=True)

In [125]:
v_df_cleaned.isna().sum()

Price     0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [146]:
v_df_cleaned.rename(columns={'Price': 'Date'}, inplace=True)

In [147]:
v_df_cleaned.sample()

,Date,Close,High,Low,Open,Volume
10,2021-01-19,195.53073120117188,197.9644367070732,193.9890613563381,196.87848282316696,9772000

In [107]:
wmt_Missing_value = wmt_df.isna().sum()
print(wmt_Missing_value)

Price     0
Close     1
High      1
Low       1
Open      1
Volume    1
dtype: int64

In [122]:
wmt_df_cleaned = wmt_df.drop(index=[0, 1]).reset_index(drop=True)

In [123]:
wmt_df_cleaned.isna().sum()

Price     0
Close     0
High      0
Low       0
Open      0
Volume    0
dtype: int64

In [143]:
wmt_df_cleaned.rename(columns={'Price': 'Date'}, inplace=True)

In [145]:
wmt_df_cleaned.sample()

,Date,Close,High,Low,Open,Volume
609,2023-06-06,48.844520568847656,48.978223732262656,48.43036395474573,48.81843378516344,15015600